### ISSUE TITLE
Charging mode (Eco/Normal) setup UI

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/openevse_wifi_gui#11]
A number of users have reported that the UI for setting up the charging mode is no intuitive. We currently have two input fields, one for solar PV gen, the other for Grid. Only one of these fields should be used.

It would be more intuitive to have a rapid button or dropdown box to select either 'Solar PV Gen' or 'Grid'.

**Comment by Suriv** [comment]
![Captura de pantalla 2019-05-20 a las 18 18 40](https://user-images.githubusercontent.com/286886/58036588-bd39c200-7b2b-11e9-9462-a7e717d6cab4.png)

Currently we have this to configure.

Let's say that the charging mode would appear if it is by GRID or it is Solar PV.

Let's say it would be two separate options. Can the two configurations exist, or if one is active, must the other one not be active?

in example:

![Captura de pantalla 2019-05-20 a las 18 26 56](https://user-images.githubusercontent.com/286886/58037149-10f8db00-7b2d-11e9-9892-8c1ab5623239.png)

**Comment by Suriv** [comment]
Any news regarding my proposal?

**Comment by jeremypoulter** [comment]
The options are mutually exclusive so probably the best UI would be an input box for the topic name and a drop down for the 'type' of feed.

**Comment by Suriv** [comment]
Ok.. 
Then I will upload proposal with the new design.

@glynhudson 
Could you close the pull? To make a climb of everything.

**Comment by glynhudson** [comment]
@Suriv apologies, I missed seeing this. This UI change will be a really nice addition. I agree with @jeremypoulter a 'feed type' drop down box would be best since either 'either' 'or  

There is no open PR for me to close.

**Comment by Suriv** [comment]
@jeremypoulter  and @glynhudson 

I had not read it well, now I understand.

![Captura de pantalla 2019-08-20 a las 13 44 07](https://user-images.githubusercontent.com/286886/63344499-e0eded80-c350-11e9-9736-766cff92ea32.png)
![Captura de pantalla 2019-08-20 a las 13 44 20](https://user-images.githubusercontent.com/286886/63344500-e0eded80-c350-11e9-9141-30bae817b424.png)

or 


Would this fit the indicated?

![Captura de pantalla 2019-08-20 a las 13 51 57](https://user-images.githubusercontent.com/286886/63344867-b6506480-c351-11e9-9c1d-1556679e0767.png)


@glynhudson About the pull, I was referring to the pull request @jeremypoulter that came up, since I am now in sync with the latest.

**Comment by glynhudson** [comment]
Nice! I prefer the toggle option on the bottom screenshot. I'm assuming the description below will change depending on the toggle setting. I reckon solar PV gen should be the default / initial option. 

Would it be possible to change `Input Value` to `MQTT topic`?

Also we should probably elaborate on what (+I/-E) means e.g 'Positive Import / Negative Export'

**Comment by jeremypoulter** [comment]
IMHO the drop down would be better as the toggle is normally used for turning things on/off, where as this is a selection of type. The selection would also allow for other types of feed in the future.

**Comment by Suriv** [comment]
> IMHO the drop down would be better as the toggle is normally used for turning things on/off, where as this is a selection of type. The selection would also allow for other types of feed in the future.

To defend.

A switch is a change from one mode to another, which is normally used for off and on, but one has already been used for example in Setup, to say manual or automatic.


On the idea of ​​future energies, I do not see that economic energies such as solar, could be a wind without blades, there is no doubt.

But is something developed to contemplate other energy than solar?

At the time it appears it could be changed to a combo but I think that when it appears it could have changed many things.

**Comment by glynhudson** [comment]
Good point @jeremypoulter, a toggle does look like a switch to enable something. A dropdown would be better. Also a drop down gives us the option to add different feed types if required in the future. 

Let's go for a drop menu :+1: 

@Suriv true, users may want to divert energy from other sources e.g wind. However, I think the majority of users will use the feature for solar PV . I would prefer to keep referring to the feature as solar PV divert, advanced users will be able to figure out they can send MQTT data from any source to adjust charging rate,

**Comment by jeremypoulter** [comment]
We have updated the UI to use a drop down to select the feed type
