### ISSUE TITLE
WiFi standalone does not work on ESP8266 using shared GUI

### ISSUE THREAD

**Issue by glynhudson** [OpenEVSE/openevse_wifi_gui#4]
After merging https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/pull/208 I noticed that the WiFi standalone mode does not seem to work on ESP8266. After loading the WiFi portal page on first power up and clicking on "WiFi Standalone Mode" the portal page just reloads as opposed to loading `home.htm`.#

I've taken a look at the source and this button is just a simple direct link to `home.htm`, any idea what's going on?

https://github.com/OpenEVSE/openevse_wifi_gui/blob/master/src/wifi_portal.htm#L64

**Comment by jeremypoulter** [comment]
The builder corrects the extension to `.html`. Will update the link.

**Comment by glynhudson** [comment]
Thanks, yes it's far better to use `.html`. I'm sure exactly why `.htm` to was used.

**Comment by glynhudson** [comment]
Thanks, now the GUI file has been updated do we need to update the static files in the repo? https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/tree/master/src/web_static

If so, what's the best procedure to do this? It also looks like the `web_static` readme is missing some content:

https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/blob/master/src/web_static/readme.md

**Comment by jeremypoulter** [comment]
Created a PR for this, with instructions, OpenEVSE/ESP8266_WiFi_v2.x#222
