### ISSUE TITLE
Update OpenEVSE lib

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/openevse_wifi_gui#7]
It should be possible to use OpenEVSE/node_openevse in place of [the included version](src/openevse.js). This will help with maintenance.

**Comment by Suriv** [comment]
contenthash?

https://webpack.js.org/guides/caching/

**Comment by Suriv** [comment]
https://github.com/OpenEVSE/node-openevse

**Comment by jeremypoulter** [comment]
Removing direct RAPI comms, so the OpenEVSE lib will no longer be needed
